runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: MySQLdb
  version: 1.2.5

handlers:
- url: /static
  static_dir: static/
- url: .*
  script: jobsphereonline.wsgi.application

builtins:
- django_wsgi: on
