# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-24 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsphereonline', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('createddate', models.DateTimeField(auto_now_add=True)),
                ('applicationoption', models.CharField(max_length=45)),
                ('applicationurl', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=45)),
                ('owner', models.CharField(max_length=45)),
                ('category', models.ManyToManyField(to='jobsphereonline.Category')),
                ('location', models.ManyToManyField(to='jobsphereonline.Location')),
                ('tag', models.ManyToManyField(to='jobsphereonline.Tag')),
            ],
        ),
    ]
