# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-25 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsphereonline', '0006_auto_20161225_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='email',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employer',
            name='password',
            field=models.CharField(default='test@test.com', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employer',
            name='logo',
            field=models.FileField(upload_to='employer/logo/'),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.ManyToManyField(to='jobsphereonline.Location'),
        ),
        migrations.AlterField(
            model_name='job',
            name='tag',
            field=models.ManyToManyField(to='jobsphereonline.Tag'),
        ),
    ]
